# Generated by Django 2.2 on 2019-04-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(choices=[('TT', 'Table Tennis'), ('FB', 'Foos Ball')], max_length=2),
        ),
    ]
